'use strict';

const wkDataEn = {
  1: { e: '🔬', s: 'Cell', w: '—', l: '—', f: [
    'The pituitary releases FSH, which starts maturation of 5–20 ovarian follicles; one will become dominant.',
    'Estrogen thickens the endometrium to 8–12 mm — an ideal lining for implantation.',
    'Folic acid reduces neural tube defect risk by about 70%; preconception dosing is 400–800 mcg daily.',
    'Cervical mucus shifts from thick to stretchy, acting as a natural filter for sperm.',
    'The nonpregnant uterus weighs about 50–60 g and will grow to roughly 1,000–1,200 g by term.',
    'LH begins rising around cycle days 6–7 and will trigger ovulation; ovulation tests measure LH surge.',
    'The dominant follicle reaches 18–25 mm before ovulation and is clearly visible on ultrasound.',
    'Start folic acid (400–800 mcg/day) if you have not already; ideally begin 1–3 months before conception.',
    'Progesterone in the luteal phase prepares the endometrium for possible implantation.',
    'A preconception checkup often includes TSH, iron, B12, folate, and infectious disease screening.',
  ]},
  2: { e: '⏳', s: 'Poppy Seed', w: '—', l: '—', f: [
    'The LH peak triggers ovulation: the follicle ruptures over 10–15 minutes, visible on ultrasound.',
    'The egg survives up to 12–24 hours; sperm may remain viable in the reproductive tract for up to 5 days.',
    'After ovulation, the ruptured follicle becomes the corpus luteum and produces progesterone.',
    'An X chromosome from the sperm yields a female embryo; a Y chromosome yields male — sex is set at fertilization.',
    'The luteal phase is typically 14 days ±1, largely independent of overall cycle length.',
    'Basal body temperature rises 0.3–0.5°F after ovulation under progesterone influence.',
    'Of hundreds of millions of sperm, only dozens reach the egg; fertilization defines the single winner.',
    'Peak conception timing is usually 2 days before ovulation through ovulation day.',
    'Fertilization occurs in the ampulla of the fallopian tube; the zygote travels to the uterus over 4–5 days.',
    'At fertilization, a unique 46-chromosome genome is formed — the foundation of your baby\'s identity.',
  ]},
  3: { e: '🌱', s: 'Poppy Seed', w: '<0.001 g', l: '0.1 mm', f: [
    'Fertilization combines 23 maternal and 23 paternal chromosomes into 46; sex is already determined.',
    'The zygote divides about every 12 hours: 1→2→4→8 cells; by day 5 there is a blastocyst (~100 cells).',
    'Blastocyst cells split into the embryoblast (future baby) and trophoblast (future placenta).',
    'Roughly half of fertilized eggs fail to implant — natural selection; yours may be continuing the journey.',
    'The zygote\'s DNA holds about 3 billion base pairs, all within a nucleus roughly 6 μm wide.',
    'Mitochondria are maternally inherited; mitochondrial DNA passes only through the maternal line.',
    'The blastocyst travels through the fallopian tube for 4–5 days, aided by cilia and tubal motility.',
    'The zona pellucida protects the early embryo from sticking to tubal walls and dissolves before implantation.',
    'Compaction begins at the 8-cell stage as cells fuse into a morula — an early coordinated step in development.',
    'The SRY gene on the Y chromosome is the main sex switch; without it, development follows the female pathway by default.',
  ]},
  4: { e: '🫘', s: 'Sesame Seed', w: '<0.001 g', l: '0.4 mm', f: [
    'Implantation begins: trophoblast enzymes help the blastocyst embed into the uterine wall.',
    'hCG production starts, rescuing the corpus luteum so progesterone continues to rise.',
    'The yolk sac is the embryo\'s first nutrient source before placental function matures.',
    'Three germ layers form: ectoderm (skin, nerves), mesoderm (muscle, bone), endoderm (gut organs).',
    'hCG typically doubles every 48–72 hours; urine pregnancy tests are often positive 10–14 days after conception.',
    'Implantation spotting occurs in 20–30% of pregnancies and is usually benign.',
    'The amniotic sac forms around the embryo — a fluid-filled environment for the months ahead.',
    'Progesterone relaxes uterine smooth muscle, helping prevent early pregnancy loss.',
    'Early nutrition comes from endometrial secretions by diffusion; maternal blood supply develops by 10–12 weeks.',
    'Progesterone-related immune tolerance helps the uterus accept the developing embryo.',
  ]},
  5: { e: '🌾', s: 'Sesame Seed', w: '<0.001 g', l: '1.5 mm', f: [
    'Neural tube closure should complete by about day 28; folic acid is critical for this process.',
    'Failure of neural tube closure can cause spina bifida; adequate folate lowers risk substantially.',
    'The primitive heart tube begins beating around 40 bpm and will soon be detectable on ultrasound.',
    'Three primary brain vesicles are visible: forebrain, midbrain, and hindbrain precursors.',
    'Chorionic villi start invading the uterine lining, establishing early placental connections.',
    'Somites form at 3–4 pairs per day and will become vertebrae, ribs, and back muscles.',
    'The allantois, precursor to bladder and umbilical structures, develops now.',
    'Eye primordia appear as ectodermal thickenings called optic placodes.',
    'Early liver cell migration from endoderm begins; the fetal liver is a major blood-forming organ until birth.',
    'The embryo is curved in a C-shape — the classic ultrasound appearance with a visible cardiac flicker.',
  ]},
  6: { e: '🧆', s: 'Lentil', w: '<0.001 g', l: '4–5 mm', f: [
    'The heart begins beating at about 100–110 bpm, often seen on transvaginal ultrasound.',
    'Pharyngeal arches develop: the first gives rise to jaw and middle ear; the second to facial muscles.',
    'The placenta starts taking over progesterone production from the corpus luteum.',
    'Arm buds appear; leg buds follow within days; fingers separate by about 8 weeks.',
    'Eyes grow from the brain toward surface ectoderm, forming the lens vesicle.',
    'At 6 weeks, hCG may range from about 1,080 to 56,500 mIU/mL; nausea can reflect robust early hormone support.',
    'Nose, mouth, and ear pits form from ectodermal placodes this week.',
    'The gut temporarily herniates into the umbilical cord because the abdominal cavity is still small.',
    'Lung precursors appear: trachea and primary bronchial buds mark the start of the respiratory tree.',
    'Neurogenesis accelerates to roughly 250,000 neurons per minute and remains high into mid-pregnancy.',
  ]},
  7: { e: '🫐', s: 'Blueberry', w: '0.8 g', l: '10 mm', f: [
    'Peak neurogenesis continues: the brain may create about 250,000 neurons per minute.',
    'Physiologic umbilical herniation is normal until about 12 weeks as the gut returns to the abdomen.',
    'All 20 primary teeth buds are forming, along with the beginnings of permanent teeth.',
    'Adrenal glands begin synthesizing cortisol and epinephrine — early endocrine activity.',
    'The retina develops initial photoreceptors and connects to the brain via the optic nerve.',
    'Eyelids begin fusing and usually remain closed until around 26 weeks.',
    'The umbilical cord forms with two arteries and one vein in Wharton\'s jelly; length is about 1 cm now.',
    'Elbows flex and early joints form; fingers are still connected by webbing.',
    'Pancreatic buds appear as ventral and dorsal outgrowths that will fuse by 8 weeks.',
    'The thymus develops here — the site where T lymphocytes mature for future immunity.',
  ]},
  8: { e: '🍒', s: 'Raspberry', w: '1 g', l: '16 mm', f: [
    'The embryo is now called a fetus; major organogenesis for this stage is largely complete.',
    'Cartilage begins replacing with bone through ossification, a process continuing into adulthood.',
    'First movements occur and may be seen on ultrasound long before you can feel them.',
    'Kidneys produce urine that enters amniotic fluid, which the fetus swallows in a continuous cycle.',
    'The heart is four-chambered with a rate around 160–170 bpm — near its pregnancy peak.',
    'After confirmed cardiac activity, miscarriage risk drops to roughly 3–5% and falls further each week.',
    'Webbing between fingers disappears through apoptosis, leaving 10 distinct digits.',
    'Olfactory bulbs form; newborns later recognize maternal scent from early exposure.',
    'Facial features including nose, lips, chin, and external ears become recognizable.',
    'Placental chorionic villi branch extensively; exchange surface may already be 1–2 m².',
  ]},
  9: { e: '🫒', s: 'Grape', w: '2 g', l: '23 mm', f: [
    'The embryonic tail disappears; interdigital webbing is gone through programmed cell death.',
    'In male fetuses, testosterone from testes begins driving external genital differentiation.',
    'Six hillocks on the head merge into recognizable external ears with helix and lobule.',
    'Heart rate may reach about 170 bpm — among the highest of the pregnancy.',
    'NIPT screening is available from 9–10 weeks using cell-free fetal DNA in maternal blood with high accuracy.',
    'Nausea often peaks as hCG peaks; hyperemesis with significant weight loss needs medical evaluation.',
    'The corpus callosum begins forming and will eventually link hundreds of millions of axons.',
    'Cartilage of the nose, ears, and intervertebral discs continues developing.',
    'The pancreas starts producing insulin, beginning glucose regulation pathways.',
    'Physiologic gut herniation reaches its maximum before the intestines return fully into the abdomen.',
  ]},
  10: { e: '🍊', s: 'Kumquat', w: '4 g', l: '31 mm', f: [
    'All major organs are formed; remaining pregnancy is mainly growth and maturation.',
    'The intestines return to the abdominal cavity; miscarriage risk after this point is often under 1–3%.',
    'Sucking reflex emerges; the fetus may suck a thumb with measurable negative pressure.',
    'Unique fingerprints form under the influence of amniotic fluid and touch.',
    'The diaphragm completes formation; the fetus practices breathing movements with fluid.',
    'Fetal blood contains HbF, which binds oxygen more efficiently than adult hemoglobin.',
    'Fingernails begin growing and may extend beyond fingertips by birth.',
    'Both primary and permanent tooth buds are developing — 52 tooth germs in total.',
    'First synapses appear in the cerebral cortex, laying groundwork for later cognition.',
    'Amniotic fluid volume is about 25 mL and will increase substantially toward the third trimester.',
  ]},
  11: { e: '🍓', s: 'Fig', w: '7 g', l: '41 mm', f: [
    'First-trimester screening (11–13 weeks) measures nuchal translucency; values above 2.5 mm raise aneuploidy concern.',
    'The fetus can taste amniotic fluid; sweet flavors increase swallowing, bitter ones decrease it.',
    'The placenta takes over hormonal support from the corpus luteum in the luteoplacental shift.',
    'Intestinal peristalsis begins while the brain rapidly forms synaptic connections.',
    'Maternal thyroid hormone (T4) supports neuronal growth; iodine deficiency can affect neurodevelopment.',
    'Chromosomal anomaly risk rises with maternal age: about 1:1,000 at 25 years versus 1:106 at 40.',
    'Facial muscles allow frowning and mouth opening visible on ultrasound.',
    'The gallbladder produces bile; the liver may occupy up to 10% of fetal body volume.',
    'External genitalia are forming but may look similar between sexes until later weeks.',
    'Nasal bone visibility on ultrasound from 11 weeks is an important first-trimester marker.',
  ]},
  12: { e: '🍋', s: 'Lime', w: '14 g', l: '54 mm', f: [
    'hCG peaks and begins declining; nausea often improves between 12 and 14 weeks.',
    'Fingerprints are fully formed and unique to this baby.',
    'The thymus produces T lymphocytes; relative thymus size is larger in the fetus than in adults.',
    'Neuromotor behaviors include yawning, sucking, swallowing, and tongue movement on 3D ultrasound.',
    'The placenta weighs about 170–200 g with villous surface area near 5 m² and will grow further.',
    'Miscarriage risk after 12 weeks with normal findings is often less than 1%.',
    'Kidneys are functional; urine enters the amniotic sac as part of fluid turnover.',
    'Chest wall breathing movements train muscles for the first breath after birth.',
    'The fetal thyroid begins synthesizing its own thyroid hormones.',
    'The Moro startle reflex is present and will persist for several months after birth.',
  ]},
  13: { e: '🍑', s: 'Peach', w: '23 g', l: '74 mm', f: [
    'The first trimester ends; many people feel better energy as the second trimester begins.',
    'The placenta produces about 25–50 mg progesterone daily — far more than the ovary alone.',
    'Auditory ossicles (malleus, incus, stapes) are nearly formed; hearing will develop soon.',
    'In female fetuses, ovaries contain about 2 million oocytes, declining to 1–2 million by birth.',
    'Synaptogenesis accelerates with thousands of new synapses forming every second.',
    'Fetal blood pressure is much lower than adult levels, with systolic values around 55–60 mmHg.',
    'The skeleton of 206 future bones is laid down as cartilage or ossification centers.',
    'Fetal cardiac output is about 20 mL/min and will rise markedly before birth.',
    'Lanugo, fine fetal hair, begins on the face to help hold vernix on the skin.',
    'Amniotic fluid volume is about 100 mL and turns over every few hours through swallowing and urination.',
  ]},
  14: { e: '🍋', s: 'Lemon', w: '43 g', l: '87 mm', f: [
    'The second trimester begins; nausea often eases and energy commonly improves.',
    'Thyroid hormones T3 and T4 regulate metabolism in nearly every fetal cell; iodine intake matters.',
    'Facial muscles produce frowns, smiles, and yawns visible on 4D ultrasound.',
    'Lanugo spreads over the body and helps retain vernix caseosa on the skin.',
    'Fetal brain plasticity is exceptionally high; sensory experiences shape developing circuits.',
    'Ossification is visible on imaging; the clavicle is among the earliest bones to calcify.',
    'Kidneys produce several milliliters of urine per hour, contributing to amniotic fluid.',
    'The pancreas synthesizes insulin and glucagon for early glucose control.',
    'Retinal rods and cones continue forming for future light detection.',
    'Maternal and fetal bloodstreams remain separated by the placental barrier and do not mix directly.',
  ]},
  15: { e: '🍏', s: 'Apple', w: '70 g', l: '100 mm', f: [
    'Auditory ossicles have ossified; the fetus begins hearing, with maternal voice especially familiar.',
    'The fetal heart pumps about 25 liters of blood daily despite a weight near 70 g.',
    'The vestibular system detects acceleration, tilt, and rotation from 15 weeks onward.',
    'First perceived movements often occur between 18 and 20 weeks in first pregnancies.',
    'Thumb sucking continues with strong pressure, training muscles for feeding after birth.',
    'Brown adipose tissue accumulates in interscapular and other regions for thermogenesis at birth.',
    'Scalp hair follicles are active; newborn hair length varies widely and remains normal either way.',
    'The fetus may move more than 50 times per hour on ultrasound, though you may not feel most yet.',
    'Skin is still thin and translucent; subcutaneous white fat increases more after 20 weeks.',
    'The brainstem respiratory center generates 30–70 fluid "breaths" per minute as practice.',
  ]},
  16: { e: '🥑', s: 'Avocado', w: '100 g', l: '116 mm', f: [
    'Myelination begins, increasing nerve impulse speed from fractions of a meter per second toward adult rates.',
    'Omega-3 DHA supports myelin; about 60% of brain dry weight is lipid, much of it DHA.',
    'Female fetuses hold about 7 million oocytes at this stage — the lifetime maximum.',
    'Brown fat in the neck and back contains UCP1 protein for heat production without shivering.',
    'Eyes rotate forward and the pupil may react to light through the abdominal wall.',
    'Glucose screening for gestational diabetes is usually done at 24–28 weeks; iron status is worth checking now.',
    'Hearing range covers roughly 250–5,000 Hz — similar to conversational speech frequencies.',
    'Placental weight may approach 100 g, nearly matching fetal weight at this point.',
    'Urination contributes 5–10 mL/hour; amniotic fluid composition reflects fetal urine increasingly.',
    'Pancreatic beta cells release insulin in response to glucose, starting endocrine regulation.',
  ]},
  17: { e: '🍐', s: 'Pear', w: '140 g', l: '130 mm', f: [
    'The cochlea completes its 2.5 turns; the fetus hears voice, heartbeat, and digestive sounds.',
    'The fetus swallows 200–500 mL of amniotic fluid daily, training kidneys, gut, and sucking.',
    'Brown fat deposits in the back and around kidneys for heat production after delivery.',
    'Skeletal ossification progresses; calcium and vitamin D support mineralization.',
    'The grasp reflex generates about 50 g of pressure — an evolutionary hold reflex seen after birth.',
    'Fundal height often approximates gestational age in centimeters ±2 cm as a growth marker.',
    'Myelinated nerve conduction reaches roughly 5–10 m/s and will continue maturing for years.',
    'Amniotic fluid volume is about 150 mL with continuous turnover through swallowing and urination.',
    'Meconium begins forming from bile, shed cells, and lanugo for passage in the first days of life.',
    'Fat stores remain a small fraction of body mass but increase steadily through the third trimester.',
  ]},
  18: { e: '🍠', s: 'Sweet Potato', w: '190 g', l: '142 mm', f: [
    'Hearing is fully functional; research shows newborns recognize maternal voice within seconds after birth.',
    'First movements for many first-time parents occur between 18 and 20 weeks — often described as fluttering.',
    'Lung branching continues with bronchioles and early alveolar development; surfactant production will follow.',
    'EEG studies suggest left-hemisphere speech processing differences may begin in utero.',
    'Yawning, swallowing, and facial expressions on 4D ultrasound reflect developing neuromotor control.',
    'Fetal urination of 5–10 mL/hour contributes significantly to amniotic fluid from mid-pregnancy onward.',
    'Retinal photoreceptors are formed; bright light through the abdomen is perceived as diffuse glow.',
    'White subcutaneous fat remains under 1% of body mass but will reach 14–16% near term.',
    'In female fetuses, uterus, fallopian tubes, and upper vagina are fully formed by 18 weeks.',
    'Regular sleep-wake cycles begin emerging, though not yet synchronized fully with maternal day-night rhythm.',
  ]},
  19: { e: '🥭', s: 'Mango', w: '240 g', l: '152 mm', f: [
    'Vernix caseosa forms: a protective coating that is mostly water, protein, and lipid with antimicrobial properties.',
    'Broca and Wernicke language areas begin developing; talking and reading aloud supports brain wiring.',
    'REM sleep may occupy 60–80% of sleep time with rapid eye movements under closed lids.',
    'Ultrasound may show up to 50 movements per hour, though only the strongest are usually felt.',
    'Fundal height is often near 19 cm; detailed anatomy scans measure head, abdomen, and femur for growth estimates.',
    'Amniotic fluid flavor reflects maternal diet; early taste exposure may influence later food preferences.',
    'Placental villous surface area may reach 6–8 m² — a vast exchange interface for oxygen and nutrients.',
    'Iron absorption improves with vitamin C and decreases with tea or calcium taken at the same time.',
    'Auditory cortex plasticity peaks; music exposure in late second trimester may support sound discrimination.',
    'The corpus callosum contains hundreds of millions of axons linking both cerebral hemispheres.',
  ]},
  20: { e: '🍌', s: 'Banana', w: '300 g', l: '250 mm', f: [
    'Halfway point: from 20 weeks, length is measured crown-to-heel, which can appear as a growth jump on charts.',
    'The uterine fundus is often at the umbilicus; fundal height commonly matches weeks ±2 cm.',
    'The fetal brain may gain about 250 mg daily as sulci and gyri begin forming.',
    'Anatomy scan at 18–21 weeks evaluates heart, brain, spine, kidneys, and facial structures in detail.',
    'Meconium accumulates in the intestine and is normally passed within 24–48 hours after birth.',
    'Sleeping on the left side improves uteroplacental blood flow compared with supine positioning after 20 weeks.',
    'Synaptogenesis may reach tens of thousands of new synapses per second during peak periods.',
    'Scalp hair is often visible on ultrasound; amount at birth varies widely and remains normal.',
    'White fat reaches about 1–2% of body mass as skin becomes less translucent.',
    'Fundal height near 20 cm is a simple clinical marker checked at prenatal visits.',
  ]},
  21: { e: '🥕', s: 'Carrot', w: '360 g', l: '270 mm', f: [
    'About 10,000 taste buds are present — similar to adulthood — detecting sweet, bitter, sour, salty, and umami.',
    'REM sleep remains a large share of rest time with eye movements suggesting active brain states.',
    'Bone marrow increasingly takes over blood cell production from the liver, making billions of cells daily.',
    'Natural killer cells are proportionally higher in fetal immunity than in adults, supporting innate defense.',
    'Hippocampal structures for memory and spatial navigation are forming and becoming functional.',
    'Maternal stress hormones can cross the placenta; calm routines support stable fetal neuroendocrine environment.',
    'DHA at roughly 300 mg/day supports myelin and membrane development in the fetal brain.',
    'The fetus distinguishes voices and music; consistent auditory exposure builds familiar sound patterns.',
    'The umbilical cord is about 25–30 cm with one to three coils; nuchal cord occurs in about 25% of pregnancies.',
    'White fat continues increasing as the fetus gains weight more rapidly in coming weeks.',
  ]},
  22: { e: '🥥', s: 'Papaya', w: '430 g', l: '280 mm', f: [
    'Newborns often orient toward the maternal voice first heard for months in utero.',
    'The Sylvian fissure between frontal, parietal, and temporal lobes becomes visible on ultrasound.',
    'The corpus callosum is fully visible on ultrasound, linking hemispheres for integrated function.',
    'Touch receptors are mature; abdominal stroking often elicits fetal movement within 20–30 seconds.',
    'After 20 weeks, blood pressure ≥140/90 mmHg with proteinuria raises preeclampsia concern and needs evaluation.',
    'Moderate exercise several times weekly is associated with lower gestational diabetes risk per ACOG guidance.',
    'Maternal melatonin helps synchronize fetal circadian rhythms through placental transfer.',
    'Maternal IgG antibodies begin crossing the placenta, providing early passive immunity.',
    'Vernix caseosa thickens as a protective lipid layer over delicate fetal skin.',
    'Bone marrow hematopoiesis accelerates to meet rising oxygen-carrying needs.',
  ]},
  23: { e: '🍊', s: 'Grapefruit', w: '500 g', l: '290 mm', f: [
    '500 g marks an early viability threshold; specialized NICU care may be considered if birth occurs now.',
    'Surfactant phospholipid synthesis begins; without adequate surfactant, alveoli collapse more easily at birth.',
    'Fetal EEG responses to speech resemble patterns seen closer to term, reflecting auditory processing maturity.',
    'GABA signaling shifts from excitatory toward inhibitory around 22–24 weeks as the CNS matures.',
    'Quiet sleep periods up to 75–90 minutes are normal; kick counts are best during active wakefulness.',
    'Heartburn affects 30–50% in the second trimester due to progesterone relaxing the lower esophageal sphincter.',
    'Stretch marks occur in most pregnancies; genetics and skin elasticity are major determinants.',
    'Amygdala and hippocampus show functional activity related to emotional and memory circuits.',
    'Maternal cardiac output increases about 30–40%, which can cause palpitations or mild breathlessness.',
    'Lung vascular development continues in preparation for gas exchange after birth.',
  ]},
  24: { e: '🌽', s: 'Ear of Corn', w: '600 g', l: '300 mm', f: [
    'At 24 weeks, NICU survival in developed settings may reach roughly 40–50% with intensive care; each week improves outcomes.',
    'The vestibular system with semicircular canals and otoliths detects motion, tilt, and rotation fully.',
    'Eyelids begin separating and will open more consistently toward 26 weeks; pupils react to light.',
    'Gestational diabetes screening with oral glucose tolerance testing is recommended at 24–28 weeks per ACOG.',
    'White subcutaneous fat reaches about 3–4% of body mass and will rise toward 14–16% at term.',
    'Placental grade 0 maturity is typical now; calcifications later in pregnancy can be physiologic.',
    'Low-dose aspirin in high-risk pregnancies may reduce preeclampsia and improve placental blood flow when prescribed.',
    'Type II pneumocytes increase surfactant production, critical for lung expansion after birth.',
    'Fingernails reach the fingertips; soft newborn mittens may help prevent scratching after delivery.',
    'Breathing practice movements continue regularly in amniotic fluid to train the diaphragm.',
  ]},
  25: { e: '🥦', s: 'Cauliflower', w: '660 g', l: '345 mm', f: [
    'Nostrils open and the fetus breathes amniotic fluid, exercising the diaphragm and intercostal muscles.',
    'The grasp reflex produces about 50 g pressure — the newborn will grip a finger strongly after birth.',
    'The limbic system with amygdala and hippocampus is active; maternal stress hormones can reach the fetus within minutes.',
    'Chronic severe maternal stress may affect fetal hippocampal development; relaxation and support strategies help.',
    'Regular moderate activity improves placental perfusion and may lower gestational diabetes risk.',
    'Leg cramps may reflect magnesium or calcium imbalance; stretching calves and hydration often help.',
    'Colostrum production may begin; occasional nipple drops in pregnancy are normal.',
    'More than 10,000 taste buds allow rich flavor experience of amniotic fluid shaped by maternal diet.',
    'Umbilical cord length is about 35–40 cm, with coils forming from fetal movement.',
    'Red blood cell production in fetal bone marrow supports rising metabolic demands.',
  ]},
  26: { e: '🥬', s: 'Head of Lettuce', w: '760 g', l: '360 mm', f: [
    'Eyelids open and pupils constrict to light; final iris color usually settles between 6 and 12 months after birth.',
    'The brain develops early thermoregulatory pathways as part of autonomic maturation.',
    'Sleep spindles on EEG resemble healthy term newborn patterns, reflecting neurologic maturity.',
    'In male fetuses, testes begin descending under INSL3 hormone influence, completing near 32–35 weeks.',
    'Visual evoked potentials show cortical responses to light flashes on specialized testing.',
    'Fetal hiccups reflect rhythmic diaphragm contractions and are common and benign.',
    'Purkinje cells in the cerebellum form vast synaptic networks for coordination and balance.',
    'Serotonin and dopamine systems linked to mood and reward begin functional activity.',
    'About 35–40% of eventual maternal IgG transfer may have occurred by 26 weeks.',
    'Braxton Hicks contractions may occur irregularly from mid-pregnancy and usually ease with rest.',
    'Maternal blood volume may be 40–50% above prepregnancy baseline, increasing cardiac workload.',
    'Glucose screening at 24–28 weeks should be completed if not already done.',
  ]},
  27: { e: '🥦', s: 'Cabbage', w: '875 g', l: '370 mm', f: [
    'Fetal EEG at 27 weeks can resemble that of a 27-week newborn, reflecting substantial brain development.',
    'Survival at 27 weeks in qualified NICUs may approach 90% with modern neonatal care.',
    'Lecithin-to-sphingomyelin (L/S) ratio is about 1.5–2.0; maternal corticosteroids can accelerate lung maturity in 24–48 hours if preterm birth threatens.',
    'Rhythmic hiccups lasting 10–30 minutes reflect diaphragm training and are commonly felt.',
    'Skin pinkens as subcutaneous fat increases and wrinkling decreases.',
    'The fetus distinguishes speech rhythm and intonation patterns in auditory processing.',
    'The cerebellum has doubled in size over recent weeks, supporting coordination and future speech timing.',
    'Newborns recognize melodies heard repeatedly in utero, supporting early auditory memory.',
    'Melatonin from the mother helps entrain fetal day-night rhythms through placental transfer.',
    'Fetal sleep includes NREM, REM, and quiet and active wakefulness in cycling patterns.',
    'Nonstress test norms from 28 weeks: baseline FHR 110–160 bpm, moderate variability, two accelerations in 20 minutes.',
    'Maternal Tdap and influenza vaccines in pregnancy provide newborn protection for several months via IgG.',
  ]},
  28: { e: '🍆', s: 'Eggplant', w: '1005 g', l: '380 mm', f: [
    'Third trimester begins above 1 kg; synaptogenesis may reach about 1.8 million synapses per second at peak.',
    'Survival beyond 28 weeks in NICU often exceeds 90%; substantial weight gain remains before term.',
    'About half of protective maternal IgG may have transferred by 28 weeks through active placental transport.',
    'Pupillary light reflex indicates integrated central nervous system function.',
    'Synaptic pruning removes less-used connections as specialized brain circuits refine.',
    'Antenatal fetal monitoring with nonstress testing is commonly used from 28 weeks when indicated.',
    'Colostrum may appear with nipple pressure; this reflects normal breast preparation for lactation.',
    'Colostrum is rich in IgA and lactoferrin compared with mature milk.',
    'The placenta produces 300–400 mg progesterone daily near peak levels to maintain uterine quiescence.',
    'Movements feel stronger as space tightens; fetal position shifts become more noticeable.',
    'Fetal iron stores accumulate toward roughly 300 mg total by birth with ongoing maternal supplementation as advised.',
    'Supine sleep is discouraged because the gravid uterus can compress the inferior vena cava.',
  ]},
  29: { e: '🫑', s: 'Butternut Squash', w: '1150 g', l: '388 mm', f: [
    'The cerebellum has grown rapidly, supporting balance, coordination, and motor precision.',
    'Six fontanelles allow skull molding during delivery while protecting the brain.',
    'Pulmonary L/S ratio near 2.0–2.5 suggests improving readiness for extrauterine breathing.',
    'Strong kicks to the ribs are common as space becomes limited; changing position often helps.',
    'Nonstress test at 29 weeks expects baseline 110–160 bpm, variability 5–25 bpm, and no concerning decelerations.',
    'Fetal iron stores approach 150 mg of the roughly 300 mg targeted by birth with continued supplementation.',
    'Amniotic fluid index normal range is often 8–20 cm; significant oligohydramnios or polyhydramnios needs evaluation.',
    'Prefrontal cortex development supports future self-control, planning, and social cognition over years.',
    'The posterior fontanelle closes around 35–36 weeks gestation; anterior fontanelle closes months after birth.',
    'Epidural analgesia can be discussed in birth planning; when appropriately used, outcomes are generally favorable.',
    'Feeding triad coordination of suck, swallow, and breathe matures toward 34 weeks.',
    'Venous thromboembolism risk rises in late pregnancy; mobility and compression stockings reduce risk when advised.',
    'Growth hormone and IGF-1 peak in late pregnancy, supporting skeletal and soft tissue growth.',
  ]},
  30: { e: '🥬', s: 'Large Cabbage', w: '1300 g', l: '397 mm', f: [
    'Lanugo disappears from the face and forehead but may persist on shoulders until near term.',
    'Red bone marrow is the primary site of hematopoiesis, producing about 100,000 red cells per second.',
    'Newborns recognize melodies heard in utero, supporting prenatal bonding through sound.',
    'Maternal melatonin patterns help synchronize fetal circadian rhythms; regular sleep schedules may help both.',
    'Corpus callosum growth continues and will complete much of its expansion in early childhood.',
    'Hippocampal long-term potentiation underlies memory formation pathways developing now.',
    'Pyramidal tract myelination reaches the lower spinal cord, supporting more coordinated movement.',
    'Placental weight is about 300–350 g at grade I maturity and may reach 500–600 g at term.',
    'Breast colostrum readiness is normal; nipple preparation beyond basic hygiene is usually unnecessary.',
    'Cervical insufficiency management with cerclage or pessary applies only when clinically indicated.',
    'Symphysis pubis pain from relaxin-mediated ligament loosening may improve with support belts and physiotherapy.',
    'Heartburn often worsens as the uterus compresses the stomach; small meals and upright posture help.',
    'Default mode network precursors may support future self-awareness and social cognition.',
    'Total pregnancy weight gain of 25–35 lb is typical with normal prepregnancy BMI per US guidelines.',
    'Nephron number reaches about 1 million — the lifelong maximum — by around 30–32 weeks.',
  ]},
  31: { e: '🍍', s: 'Pineapple', w: '1500 g', l: '413 mm', f: [
    'Surfactant levels are often adequate enough that RDS risk drops significantly if birth occurs at 31 weeks.',
    'The liver stores iron for the first months of life, which is why breast milk iron content is relatively low.',
    'Neural connectivity may form around 1.8 million synapses per second during peak synaptogenesis.',
    'BDNF neurotrophin supports brain development; DHA intake correlates with higher BDNF levels.',
    'Insular cortex development supports interoception and body awareness beginning in utero.',
    'Lanugo largely leaves the body while vernix accumulates in skin folds as antimicrobial protection.',
    'Kick-count methods such as ten movements within two hours during active periods help monitor wellbeing.',
    'Fetal hemoglobin near 31 weeks should remain adequate; maternal anemia screening continues in the third trimester.',
    'The fetus is often more active evenings and overnight, a pattern that may continue in early infancy.',
    'Coagulation factors and platelet counts approach newborn ranges in preparation for delivery.',
    'Pain matrix pathways involving thalamus and cortex are formed; nociceptive processing is present.',
    'Maternal plasma volume may be 45% above baseline, increasing fatigue and cardiac workload.',
    'Most fetuses are cephalic by 36 weeks, though position can still change until later in pregnancy.',
    'Physiologic ankle edema in evening hours occurs in most pregnancies and improves with elevation.',
    'Optional 3D ultrasound may show facial features in detail during this period.',
  ]},
  32: { e: '🍈', s: 'Squash', w: '1700 g', l: '425 mm', f: [
    'About 80% of fetuses are head-down by 32 weeks; cephalic presentation reaches roughly 96% by 36 weeks.',
    'Fingernails reach the fingertips; newborn scratching is common without soft mitts.',
    'Surfactant production makes spontaneous breathing likely if birth occurs at 32 weeks with NICU support.',
    'Skin becomes pink and opaque as subcutaneous fat fills the dermis.',
    'The cerebellum is functionally active for balance, coordination, and speech rhythm development.',
    'The posterior fontanelle closes near term; the anterior fontanelle remains open for months after birth.',
    'Melatonin receptors in the fetal brain support circadian rhythm entrainment from maternal signals.',
    'Neutrophil counts approach adult ranges as part of mature innate immune readiness.',
    'Fetal functional MRI at 32 weeks may show seven major brain networks similar to adult organization.',
    'Newborn stomach capacity is only 10–15 mL at birth, matching colostrum volumes perfectly.',
    'Perineal massage from 34–35 weeks may reduce perineal trauma when performed as directed.',
    'Placental grade I–II calcifications can be normal and reflect maturation rather than dysfunction alone.',
    'Breech presentation at 32 weeks may be managed with exercises, external cephalic version, or planned cesarean depending on context.',
    'Carpal tunnel symptoms often peak from fluid retention; wrist splints and elevation may help at night.',
    'Hospital bag preparation by 34–36 weeks includes documents, comfort items, and newborn essentials.',
  ]},
  33: { e: '🍍', s: 'Pineapple', w: '1900 g', l: '435 mm', f: [
    'Amniotic fluid volume peaks around 800–1,000 mL and may gradually decline toward term.',
    'IgG transfer accelerates; fetal levels can exceed maternal levels near 37–38 weeks.',
    'Maternal Tdap between 27–36 weeks protects the newborn from pertussis for the first months of life.',
    'Sleep spindles on EEG reflect thalamocortical maturation and organized sleep architecture.',
    'Fetal day-night distinction follows maternal melatonin; consistent maternal sleep supports rhythm.',
    'Supine positioning can reduce venous return and uteroplacental perfusion and should be avoided for sleep.',
    'Suck-swallow-breathe coordination nears readiness for feeding by about 34 weeks gestation.',
    'Bishop score assesses cervical ripeness; higher scores suggest readiness for labor induction when indicated.',
    'Group B strep screening at 35–37 weeks guides intrapartum antibiotic prophylaxis when positive.',
    'Braxton Hicks contractions may intensify but remain irregular without progressive cervical change.',
    'True labor signs include regular contractions, ruptured membranes, and progressive pain unlike Braxton Hicks.',
    'External cephalic version for breech presentation is often attempted at 36–37 weeks with specialist care.',
    'Fiber-rich diet helps constipation, which affects 30–40% of pregnancies in the third trimester.',
    'Vitamin D supplementation for newborns is commonly 400 IU daily starting in the first weeks of life.',
    'Deep breathing techniques such as 4-7-8 patterns support labor pain coping skills when practiced early.',
  ]},
  34: { e: '🎃', s: 'Cantaloupe', w: '2100 g', l: '450 mm', f: [
    'Central nervous system maturity supports synchronized sucking, swallowing, and breathing for feeding.',
    'Fetal lactase reaches about 30% maturity and approaches full term levels by 40 weeks.',
    'Fetal cortisol rises physiologically to mature lungs and store glycogen for the transition to extrauterine life.',
    'Adrenal catecholamines prepare the stress response needed at birth.',
    'Pain pathways through thalamus and cortex are fully formed with functional nociceptive processing.',
    'About 206 of 270 skeletal elements are ossified; others remain cartilaginous until childhood.',
    'Weight gain of roughly 220–250 g per week is typical now; the fetus may double weight before birth.',
    'Functional brain networks at 34 weeks resemble adult organization on advanced imaging studies.',
    'Lanugo clears from the face and mostly remains on shoulders until 38–40 weeks.',
    'Gestational diabetes managed with diet may require insulin if glycemic targets are not met — insulin is safe in pregnancy.',
    'Hospital bag should be ready by 34–36 weeks with identification and prenatal records accessible.',
    'Perineal massage from 34–35 weeks daily may reduce severe perineal tears in some studies.',
    'Upright and hands-and-knees labor positions may shorten second stage and reduce some interventions.',
    'Colostrum expression before birth is normal and does not require special nipple preparation routines.',
    'Neonatal glycogen stores of 5–6 g/kg support glucose needs in the first hours after birth.',
    'Postpartum depression affects 10–15% of parents and is treatable with support and medical care.',
  ]},
  35: { e: '🍉', s: 'Honeydew Melon', w: '2350 g', l: '462 mm', f: [
    'Pulmonary maturity markers such as L/S ratio above 4 and positive phosphatidylglycerol support spontaneous breathing at term.',
    'White fat comprises about 15% of body mass, creating the rounded cheeks typical of newborns.',
    'Movements shift toward rolling and stretching rather than sharp kicks as space tightens.',
    'Ten distinct movements daily is a common kick-count goal; Cardiff method uses time to ten movements.',
    'Neutrophils and NK cells approach adult immune readiness for extrauterine exposure.',
    'Shoulder lanugo usually disappears by 38–40 weeks though some babies are born with fine back hair.',
    'Meconium fills the intestine and is normally passed within 24–48 hours after birth.',
    'EEG at 35 weeks shows continuous activity reflecting mature cortical function.',
    'Prodromal labor signs include lightening, mucous plug loss, and increased Braxton Hicks contractions.',
    'Hospital bag in the car by 36 weeks with documents in an easy-access pocket is practical preparation.',
    'Vitamin K 1 mg intramuscular at birth prevents hemorrhagic disease of the newborn.',
    'Newborn hearing screening before discharge detects congenital hearing loss early.',
    'Immediate skin-to-skin contact for at least one hour stabilizes temperature, heart rate, breathing, and glucose.',
    'Middle cerebral artery Doppler may assess fetal anemia or redistribution when clinically indicated.',
    'Group B strep screening at 35–37 weeks guides intrapartum penicillin when results are positive.',
    'Routine episiotomy is not recommended; perineal massage and controlled pushing reduce trauma risk.',
  ]},
  36: { e: '🍉', s: 'Romaine Lettuce', w: '2600 g', l: '473 mm', f: [
    'Early term begins at 36 weeks; brain volume may increase about 35% between 36 and 40 weeks.',
    'Lungs are generally ready for spontaneous breathing; RDS risk at 36 weeks is relatively low with modern care.',
    'Lightening as the head engages may ease breathing but increase bladder pressure.',
    'The cervix ripens under prostaglandins, becoming softer and sometimes shorter before labor.',
    'About 95% of maternal IgG may have transferred, providing passive immunity for early infancy.',
    'Nuchal cord occurs in 25–30% of pregnancies and is usually managed safely at delivery.',
    'Placenta previa diagnosed earlier often resolves with uterine growth by 36 weeks on repeat imaging.',
    'Group B strep positive status warrants intrapartum antibiotics to reduce neonatal sepsis risk.',
    'True labor contractions become regular, longer, and stronger unlike Braxton Hicks.',
    'Colostrum is ready; early breastfeeding within the first hour supports lactation and bonding.',
    'Fetal heart rate of 110–160 bpm is often audible with a fetoscope through the abdomen.',
    'Scalp hair averages 1–2 cm at birth with wide normal variation.',
    'Vernix in skin folds should be left on initially after birth for antimicrobial and moisturizing benefits.',
    'Signs of labor include regular contractions every 5–10 minutes, ruptured membranes, or heavy bleeding needing evaluation.',
    'Active management of the third stage with oxytocin reduces postpartum hemorrhage risk per WHO guidance.',
    'All newborn reflexes including rooting, suck, grasp, and Moro are present and practiced in utero.',
  ]},
  37: { e: '🍉', s: 'Swiss Chard', w: '2900 g', l: '483 mm', f: [
    'Early term begins at 37 weeks per WHO; optimal outcomes for elective delivery are often at 39–40 weeks.',
    'Fetal cortisol rises and may participate in triggering labor through placental signaling pathways.',
    'Ear cartilage is firm, a Ballard maturity sign used in newborn assessment.',
    'Nails may extend beyond fingertips; newborn mitts prevent scratching.',
    'The sucking reflex at the breast in the first 30–60 minutes supports the golden hour of feeding.',
    'Colostrum contains IgA at 12–16 g/L compared with lower levels in mature milk.',
    'HbF will gradually transition to HbA over the first 3–6 months after birth.',
    'Skin-to-skin contact immediately after birth improves thermoregulation and breastfeeding success.',
    'Delayed cord clamping for 1–3 minutes may transfer an additional 80–100 mL of blood to the newborn.',
    'Apgar scores at 1 and 5 minutes assess heart rate, breathing, tone, reflexes, and color — not a beauty contest.',
    'The first breath is triggered by rising CO2, temperature change, and cord clamping at delivery.',
    'Rh-negative mothers with Rh-positive infants may receive anti-D immunoglobulin within 72 hours postpartum.',
    'Vitamin K prophylaxis at birth prevents vitamin K deficiency bleeding in newborns.',
    'Newborn metabolic screening on a heel stick at 24–72 hours detects treatable conditions early.',
    'Vaginal birth exposes the infant to maternal Lactobacillus, seeding the microbiome differently than cesarean birth.',
    'Welcome to the final weeks — fetal systems are largely ready for birth while brain growth continues.',
  ]},
  38: { e: '🍉', s: 'Leek', w: '3100 g', l: '492 mm', f: [
    'Vernix remains mainly in flexion creases such as groin and axilla and should not be washed off immediately.',
    'IgG transfer may reach about 0.5 g/day, protecting the newborn for the first 3–6 months of life.',
    'The first breath requires high negative pressure and surfactant to expand alveoli successfully.',
    'The ductus arteriosus and foramen ovale close over hours to days as circulation converts to adult pattern.',
    'Frequent breastfeeding stimulates milk production; day-one stomach volume is only 5–7 mL per feed.',
    'Early skin-to-skin contact normalizes temperature, heart rate, respiration, and blood glucose.',
    'Apgar 8–10 is excellent; lower initial scores may improve with stabilization and do not predict long-term outcome alone.',
    'Newborns normally lose 5–10% of birth weight and regain it by 7–10 days with adequate feeding.',
    'Physiologic jaundice peaks around days 3–4 as fetal hemoglobin breaks down; phototherapy treats higher levels.',
    'Metabolic newborn screening detects hypothyroidism, PKU, and other conditions treatable when found early.',
    'Postpartum depression may begin within weeks after birth and responds well to therapy and medical treatment.',
    'Delayed cord clamping increases iron stores by roughly 30–50 mg compared with immediate clamping.',
    'The uterus involutes over 6–8 weeks postpartum while lochia gradually decreases.',
    'Postpartum hair shedding around 2–4 months is telogen effluvium and usually resolves by 6–12 months.',
    'Birth plan review including pain management, feeding goals, and support persons helps reduce stress.',
    'Hospital route, parking, and admission procedures are worth confirming before labor begins.',
  ]},
  39: { e: '🎃', s: 'Mini Watermelon', w: '3300 g', l: '500 mm', f: [
    'Full term by ACOG is 39–0 through 40–6 weeks; brain and lung maturity are optimal in this window.',
    'Elective delivery before 39 weeks without medical indication is generally discouraged because of neonatal risks.',
    'Labor cascade involves fetal cortisol, prostaglandins, cervical ripening, and coordinated uterine contractions.',
    'Mucous plug loss with blood-tinged discharge may precede labor by hours or days.',
    'False labor contractions are irregular, do not intensify progressively, and often stop with movement or hydration.',
    'Ruptured membranes require prompt evaluation even without contractions due to infection risk over time.',
    'Upright labor and position changes may shorten the first stage of labor in many patients.',
    'Water immersion during the first stage may reduce pain for some laboring patients when available.',
    'Prodromal signs include lightening, loose stools, nesting energy, and mild weight loss from fluid shift.',
    'Placental grade III calcifications can be physiologic at term and do not alone indicate placental failure.',
    'Active management of the third stage with uterotonic medication reduces postpartum hemorrhage incidence.',
    'Newborn procedures including vitamin K, eye prophylaxis where used, hearing screen, and metabolic testing occur in hospital.',
    'Early breastfeeding with colostrum transitions to transitional then mature milk over the first two weeks.',
    'Skin-to-skin in the first 30–60 minutes supports latch, temperature, and oxytocin release for both parent and baby.',
    'Vaginal birth contributes initial microbiome colonization that differs from cesarean-born infants.',
    'You have reached the final week before due date — body and baby are prepared for meeting.',
  ]},
  40: { e: '👶', s: 'Watermelon', w: '3400 g', l: '510 mm', f: [
    'Due date today! Only about 4–5% of babies arrive exactly on the estimated date; term birth spans 37–42 weeks.',
    'Hepatic glycogen stores of 5–6 g/kg support glucose needs until feeding establishes after birth.',
    'At birth, fetal circulation converts within seconds as the ductus arteriosus and foramen ovale close.',
    'Apgar scoring at 1 and 5 minutes provides a quick newborn adaptation assessment at delivery.',
    'Skin-to-skin contact for at least one hour stabilizes vital signs and supports early breastfeeding.',
    'Colostrum volumes of 2–5 mL per feed match the newborn stomach size on day one.',
    'Physiologic jaundice affects most term newborns, peaking around day 3–4 as bilirubin rises and then falls.',
    'Hospital newborn care includes hearing screening, vitamin K, and metabolic heel-stick testing before discharge.',
    'Breast milk volume typically increases to 100–300 mL daily by the end of the first week with frequent feeding.',
    'Normal postpartum blood loss is up to about 500 mL after vaginal birth; heavier bleeding needs urgent evaluation.',
    'The newborn gut is initially sterile and is colonized at birth through skin, vaginal, and environmental exposure.',
    'Weight loss of 5–10% after birth is expected with regain by 7–10 days when feeding is effective.',
    'Postpartum depression affects 10–15% of new parents and improves with treatment — reaching out is important.',
    'Newborn reflexes including suck, root, grasp, and Moro are present and fade over the first months.',
    'Vision at birth focuses best at 8–10 inches — the distance from breast to face during feeding.',
    'The newborn recognizes the maternal voice heard for months in utero from the first moments after birth.',
    'Congratulations — 40 weeks of growth, adaptation, and preparation have led to this meeting.',
    'Welcome to parenthood: the fourth trimester of feeding, sleep, and bonding begins now.',
    'Immediate postpartum recovery includes uterine cramping, lochia, and hormonal shifts that normalize over weeks.',
    'You completed an extraordinary journey — your baby is here and a new chapter begins today.',
  ]},
};
